apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-ambassador
  name: multi-ambassador
spec:
  containers:
  - image: nginx:alpine
    name: ambassador
    resources: {}
    volumeMounts:
    - name: nginx-config
      mountPath: etc/nginx/conf.d
      readOnly: true
    ports:
    - containerPort: 80
  - image: nginx:alpine
    name: backend
    args: ["curl","localhost/test"]
    ports:
    - containerPort: 8080
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
      items:
      - key: default.conf
        path: default.conf
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
